on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # steps for building assets
      - run: tar -C src -cJf unraid-tailscale-utils-${{ github.event.release.name}}.txz *

      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: unraid-tailscale-utils-${{ github.event.release.name}}.txz
  